services:
  yaml_parser:
    class: Symfony\Component\Yaml\Yaml

  pbc_modify_docker_file:
    class: SprykerSdk\Sdk\Extension\Service\PbcDockerFileModifier
    arguments:
      - '@yaml_parser'

  pbc_modify_composer_file:
    class: SprykerSdk\Sdk\Extension\Service\PbcComposerFileModifier

  generate_pbc_change_name_command:
    class: SprykerSdk\Sdk\Extension\Tasks\Commands\ChangeNamesCommand
    arguments:
      - '@pbc_modify_composer_file'
      - '@pbc_modify_docker_file'

  generate_pbc_check_git_command:
    class: SprykerSdk\Sdk\Extension\Tasks\Commands\CheckGitCommand

  generate_pbc_command:
    class: SprykerSdk\Sdk\Extension\Tasks\Commands\GeneratePbcCommand

  generate_pbc_change_php_version_command:
    class: SprykerSdk\Sdk\Extension\Tasks\Commands\ChangePhpVersionCommand
    arguments:
      - '@pbc_modify_composer_file'
      - '@pbc_modify_docker_file'

  generate_pbc_add_aop_sdk_command:
    class: SprykerSdk\Sdk\Extension\Tasks\Commands\AddAcpSdkCommand
    arguments:
      - '@pbc_modify_composer_file'

  generate_pbc_allow_default_composer_plugins_command:
    class: SprykerSdk\Sdk\Extension\Tasks\Commands\AllowDefaultComposerPluginCommand
    arguments:
      - '@pbc_modify_composer_file'

  generate_pbc_update_dependencies_command:
    class: SprykerSdk\Sdk\Extension\Tasks\Commands\UpdateDependenciesCommand

  generate_pbc_add_docker_sdk_command:
    class: SprykerSdk\Sdk\Extension\Tasks\Commands\AddDockerSdkCommand

  generate_pbc_next_steps_command:
    class: SprykerSdk\Sdk\Extension\Tasks\Commands\NextPbcStepsCommand

  generate_pbc:
    class: SprykerSdk\Sdk\Extension\Tasks\GeneratePbcTask
    tags: [ 'sdk.task' ]
    arguments:
      $commands:
        - '@generate_pbc_check_git_command'
        - '@generate_pbc_command'
        - '@generate_pbc_change_name_command'
        - '@generate_pbc_change_php_version_command'
        - '@generate_pbc_add_aop_sdk_command'
        - '@generate_pbc_allow_default_composer_plugins_command'
        - '@generate_pbc_update_dependencies_command'
        - '@generate_pbc_add_docker_sdk_command'
        - '@generate_pbc_next_steps_command'
