services:

  clone_internal_project_repository_command:
    class: SprykerSdk\SdkTasksBundle\Tasks\Commands\CloneInternalProjectRepositoryCommand

  update_docker_submodule_command:
    class: SprykerSdk\SdkTasksBundle\Tasks\Commands\UpdateDockerSubmoduleCommand

  internal_business_model_installer_task:
    class: SprykerSdk\SdkTasksBundle\Tasks\InternalProjectInstallerTask
    tags: ['sdk.task']
    arguments:
      $commands:
        - '@check_git_command'
        - '@check_docker_command'
        - '@check_mutagen_for_mac_command'
        - '@clone_internal_project_repository_command'
        - '@update_docker_submodule_command'
        - '@add_docker_sdk_command'
        - '@business_model_arm_command'
        - '@docker_init_up_steps_command'

  internal_project_value_resolver:
    class: SprykerSdk\SdkTasksBundle\ValueResolvers\InternalProjectValueResolver
    tags: [ "sdk.value_resolver" ]
    arguments:
      - '@value_receiver'