name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - feature/[a-z]+-[0-9]+/dev-*
  workflow_dispatch:

jobs:
  validation-8:
    name: "CS, PHPStan, Security"
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.0'
          - '8.1'

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: json
          tools: composer:v2

      - name: Composer get cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer validate
        run: composer validate

      - name: Composer version
        run: |
          composer --version
          composer install

      - name: Run PHPStan
        run: composer stan

      - name: Run CodeStyle checks
        run: composer cs-check

  validation-74:
    name: "CS, PHPStan, Security"
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '7.4'

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: json
          tools: composer:v2

      - name: Composer get cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer validate
        run: composer validate

      - name: Composer version
        run: |
          composer --version
          composer lowest-setup

      - name: Run PHPStan
        run: composer stan

      - name: Run CodeStyle checks
        run: composer cs-check
